### ISSUE TITLE
Trop de if imbriqués dans la fonction handle_booking_form

### ISSUE THREAD

**Issue by fmassot** [rjNemo/villafleurie#5]
La fonction est difficile à lire, ça mériterait un refactoring en suivant l'idée de [fail fast](https://en.wikipedia.org/wiki/Fail-fast)

https://github.com/rjNemo/villafleurie/blob/a91914a6409d11bd0e25d92b2d9f88906a8eb40d/rental/views/booking.py#L18

**Comment by rjNemo** [comment]
Merci du retour.
Je reconnais qu'entre les if et try statements c'est difficile de se retrouver.
