### ISSUE TITLE
Vue contact.view améliorée ?

### ISSUE THREAD

**Issue by fmassot** [rjNemo/villafleurie#6]
Je suis vraiment pas fan de ce type de vue même si je sais qu'on a pas trop le choix dans django. Une idée d'une autre implémentation  https://github.com/rjNemo/villafleurie/blob/a91914a6409d11bd0e25d92b2d9f88906a8eb40d/rental/views/contact.py#L7

`

    form = ContactForm(request.POST) if request.method == 'POST' else ContactForm()
    
    if request.method == 'POST' and form.is_valid():
            contact = Contact.objects.create(
                name=form.cleaned_data['name'],
                email=form.cleaned_data['email'],
                subject=form.cleaned_data['subject'],
                message=form.cleaned_data['message']
            )
            contact.send_confirmation()
            contact.send_notification()
            return render(request, 'rental/contact_merci.html', {})

    return render(request, 'rental/contact.html', {'form': form})`

ou

`

    form = ContactForm(request.POST) if request.method == 'POST' else ContactForm()
    
    if request.method == 'GET' or not form.is_valid():
         return render(request, 'rental/contact.html', {'form': form})`

     contact = Contact.objects.create(
                name=form.cleaned_data['name'],
                email=form.cleaned_data['email'],
                subject=form.cleaned_data['subject'],
                message=form.cleaned_data['message']
            )
      contact.send_confirmation()
      contact.send_notification()

      return render(request, 'rental/contact_merci.html', {})`

**Comment by rjNemo** [comment]
L'implémentation originale est un peu trop impérative.
 
C'est à tester mais je préfère la seconde proposition.
